---
apiVersion: v1
kind: Secret
metadata:
  namespace: sensiboard
  name: sensiboard-api-secrets
type: Opaque
stringData:
  databaseUrl: $DATABASE_URL
  jwtSecret: $JWT_SECRET
  signupActive: $SIGNUP_ACTIVE
  awsSecretAccessKey: $AWS_SECRET_ACCESS_KEY
  awsAccessKeyId: $AWS_ACCESS_KEY_ID
  spaceRegion: $SPACE_REGION
  spaceEndpoint: $SPACE_ENDPOINT
  spaceBucket: $SPACE_BUCKET
  fileServerUrl: $FILE_SERVER_URL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensiboard-api-deployment
  namespace: sensiboard
  labels:
    app: sensiboard-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sensiboard-api
  template:
    metadata:
      labels:
        app: sensiboard-api
    spec:
      containers:
      - name: sensiboard-api
        image: $API_IMAGE
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: sensiboard-api-secrets
              key: databaseUrl
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: sensiboard-api-secrets
              key: jwtSecret
        - name: SIGNUP_ACTIVE
          valueFrom:
            secretKeyRef:
              name: sensiboard-api-secrets
              key: signupActive

        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: sensiboard-api-secrets
              key: awsSecretAccessKey
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: sensiboard-api-secrets
              key: awsAccessKeyId
        - name: SPACE_REGION
          valueFrom:
            secretKeyRef:
              name: sensiboard-api-secrets
              key: spaceRegion
        - name: SPACE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: sensiboard-api-secrets
              key: spaceEndpoint
        - name: SPACE_BUCKET
          valueFrom:
            secretKeyRef:
              name: sensiboard-api-secrets
              key: spaceBucket

        - name: FILE_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: sensiboard-api-secrets
              key: fileServerUrl
---
apiVersion: v1
kind: Service
metadata:
  name: sensiboard-api
  namespace: sensiboard
spec:
  selector:
    app: sensiboard-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sensiboard-api-ingress
  namespace: sensiboard
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - $API_HOSTNAME
    secretName: sensiboard-api-tls-secret
  rules:
  - host: $API_HOSTNAME
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sensiboard-api
            port:
              name: web
