---
apiVersion: v1
kind: Secret
metadata:
  namespace: sensiboard
  name: sensiboard-api-secrets
type: Opaque
stringData:
  databaseUrl: $DATABASE_URL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensiboard-api-deployment
  namespace: sensiboard
  labels:
    app: sensiboard-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sensiboard-api
  template:
    metadata:
      labels:
        app: sensiboard-api
    spec:
      containers:
      - name: sensiboard-api
        image: $API_IMAGE
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: sensiboard-api-secrets
              key: databaseUrl
---
apiVersion: v1
kind: Service
metadata:
  name: sensiboard-api
  namespace: sensiboard
spec:
  selector:
    app: sensiboard-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sensiboard-api-ingress
  namespace: sensiboard
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - $API_HOSTNAME
    secretName: sensiboard-api-tls-secret
  rules:
  - host: $API_HOSTNAME
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sensiboard-api
            port:
              name: web
