---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensiboard-deployment
  namespace: sensiboard
  labels:
    app: sensiboard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sensiboard
  template:
    metadata:
      labels:
        app: sensiboard
    spec:
      containers:
      - name: sensiboard
        image: $APP_IMAGE
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sensiboard
  namespace: sensiboard
spec:
  selector:
    app: sensiboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sensiboard-ingress
  namespace: sensiboard
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - $HOSTNAME
    secretName: sensiboard-tls-secret
  rules:
  - host: $HOSTNAME
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sensiboard
            port:
              name: web
